# Generated by Django 3.1.7 on 2021-04-07 14:07

import awardsapp.models
import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-post_date']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='portfolio_link',
            new_name='link',
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Project screenshot'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('design', awardsapp.models.IntegerRangeField()),
                ('usability', awardsapp.models.IntegerRangeField()),
                ('content', awardsapp.models.IntegerRangeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='awardsapp.project')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awardsapp.profile')),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
    ]
