# Generated by Django 3.1.7 on 2021-04-08 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0002_auto_20210407_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='content_score',
        ),
        migrations.RemoveField(
            model_name='project',
            name='design_score',
        ),
        migrations.RemoveField(
            model_name='project',
            name='usability_score',
        ),
        migrations.RemoveField(
            model_name='project',
            name='voters',
        ),
    ]
